### ISSUE TITLE
Smart Importer "working" but not generating predictions

### ISSUE THREAD

**Issue by fapapa** [beancount/smart_importer#137]
I've got beancount 3 and beangulp installed and working. I'm now trying to get Smart Importer to work with that setup. I've applied the suggestions given in other issues of this repo, which got things "working" but it's not producing any useful predictions, despite having plenty of training data. The command I run is:

```
python import.py extract --existing /Users/fabio/finances/fabio_and_emily.beancount ~/Downloads/finances
```

This is my `import.py`:

```
#!/usr/bin/env python3

from importers import ofx

from beancount.core import data
import beangulp

import logging
logging.basicConfig(level=logging.DEBUG)

from smart_importer import PredictPostings

bank_chequing = ofx.Importer(
    "xxx",
    "Assets:CA:mybank:chequing"
)

bank_visa = ofx.Importer(
    "xxx",
    "Liabilities:CA:mybank:visa"
)

importers = [
    bank_chequing,
    bank_visa,
]

def clean_up_descriptions(extracted_entries):
    """Example filter function; clean up cruft from narrations.

    Args:
      extracted_entries: A list of directives.
    Returns:
      A new list of directives with possibly modified payees and narration
      fields.
    """
    clean_entries = []
    for entry in extracted_entries:
        if isinstance(entry, data.Transaction):
            if entry.narration and " / " in entry.narration:
                left_part, _ = entry.narration.split(" / ")
                entry = entry._replace(narration=left_part)
            if entry.payee and " / " in entry.payee:
                left_part, _ = entry.payee.split(" / ")
                entry = entry._replace(payee=left_part)
        clean_entries.append(entry)
    return clean_entries


def smart_importer_hook(extracted, existing):
    """Hook to be used with beangulp."""
    processed_entries = []
    for filename, entries, account, importer in extracted:
        predictor = PredictPostings()
        predicted = predictor(importer, filename, entries, existing)
        processed_entries.append([filename, predicted, account, importer])
    return processed_entries


def process_extracted_entries(extracted_entries_list, ledger_entries):
    """Example filter function; clean up cruft from narrations.

    Args:
      extracted_entries_list: A list of (filename, entries) pairs, where
        'entries' are the directives extract from 'filename'.
      ledger_entries: If provided, a list of directives from the existing
        ledger of the user. This is non-None if the user provided their
        ledger file as an option.
    Returns:
      A possibly different version of extracted_entries_list, a list of
      (filename, entries), to be printed.
    """
    return [(filename, clean_up_descriptions(entries), account, importer)
            for filename, entries, account, importer in extracted_entries_list]


hooks = [smart_importer_hook, process_extracted_entries]


if __name__ == '__main__':
    ingest = beangulp.Ingest(importers, hooks)
    ingest()
```

As mentioned, this all runs without issue. This is what is output by the debug logger:

```
DEBUG:root:Running PredictPostings for file /Users/fabio/Downloads/finances/visa.qfx
DEBUG:smart_importer.predictor:Loaded training data with 1186 transactions for account Liabilities:CA:mybank:visa, filtered from 1763 total transactDEBUG:smart_importer.predictor:Loaded training data with 1186 transactions for account Liabilities:CA:mybank:visa, filtered from 1763 total transactDEBUG:smart_importer.predictor:Trained the machine learning model.
DEBUG:smart_importer.predictor:Apply predictions with pipeline
DEBUG:smart_importer.predictor:Added predictions to 602 transactions
DEBUG:root:Running PredictPostings for file /Users/fabio/Downloads/finances/chequing.qfx
DEBUG:smart_importer.predictor:Loaded training data with 430 transactions for account Assets:CA:mybank:chequing, filtered from 1763 total transactions
DEBUG:smart_importer.predictor:Trained the machine learning model.
DEBUG:smart_importer.predictor:Apply predictions with pipeline
DEBUG:smart_importer.predictor:Added predictions to 226 transactions
```

So it's actually loading and filtering the training data correctly. And it thinks it's applying postings predictions. But unfortunately all the entries that are produced have just the one posting, which is the account given by the importer. Maybe I'm doing something wrong. Please let me know if more information is needed.

**Comment by tarioch** [comment]
Can you try with the smart importer way to put in hooks? Just trying to figure out what goes wrong.

```python
from smart_importer import apply_hooks, PredictPostings

importers = [
    apply_hooks(bank_chequing, [PredictPostings()]),
    apply_hooks(bank_visa, [PredictPostings()]),
]
```

**Comment by fapapa** [comment]
Thanks for the response. That doesn't work; I get:

```
Traceback (most recent call last):
  File "/Users/fabiopapa/finances/import.py", line 109, in <module>
    ingest()
    ~~~~~~^^
  File "/Users/fabiopapa/dev/beangulp/examples/.venv/lib/python3.13/site-packages/beangulp/__init__.py", line 282, in __call__
    return self.cli()
           ~~~~~~~~^^
  File "/Users/fabiopapa/dev/beangulp/examples/.venv/lib/python3.13/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/fabiopapa/dev/beangulp/examples/.venv/lib/python3.13/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/Users/fabiopapa/dev/beangulp/examples/.venv/lib/python3.13/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/fabiopapa/dev/beangulp/examples/.venv/lib/python3.13/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fabiopapa/dev/beangulp/examples/.venv/lib/python3.13/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/Users/fabiopapa/dev/beangulp/examples/.venv/lib/python3.13/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/fabiopapa/dev/beangulp/examples/.venv/lib/python3.13/site-packages/beangulp/__init__.py", line 105, in _extract
    extracted = func(extracted, existing_entries)
TypeError: 'Importer' object is not callable
```

Also tried this with **no** hooks:

```
importers = [
    apply_hooks(scotia_chequing, [PredictPostings()]),
    apply_hooks(scotia_visa, [PredictPostings()]),
]
```

Which also failed:

```
* /Users/fabio/Downloads/finances/Chequing_7721_122824.qfx ...DEBUG:smart_importer.hooks:Calling the importer's extract method.
  ERROR
  Exception in importer code.
  Traceback (most recent call last):
    File "/Users/fabio/dev/beangulp/examples/.venv/lib/python3.13/site-packages/beangulp/__init__.py", line 86, in _extract
      entries = extract.extract_from_file(importer, filename, existing_entries)
    File "/Users/fabio/dev/beangulp/examples/.venv/lib/python3.13/site-packages/beangulp/extract.py", line 40, in extract_from_file
      entries = importer.extract(filename, existing_entries)
    File "/Users/fabio/dev/beangulp/examples/.venv/lib/python3.13/site-packages/smart_importer/hooks.py", line 40, in patched_extract_method
      imported_entries = unpatched_extract(
          file, existing_entries=existing_entries
      )
  TypeError: Importer.extract() got an unexpected keyword argument 'existing_entries'
```

**Comment by tarioch** [comment]
Can you try to install my branch and try again

`pip install git+https://github.com/beancount/smart_importer@feature/beancount_3`

**Comment by fapapa** [comment]
OK, yes, that appears to have done the trick! Caveat that I had installed beangulp by cloning the repo, and that uses its own version of smart_importer, so I just ended up making your changes to the smart importer files in the beangulp codebase rather than installing from your branch. There's probably a better way but I know next to nothing about python.

Thanks so much for figuring out a fix so quickly. Hope to see the fix release shortly.

**Comment by tarioch** [comment]
It's released now
