### ISSUE TITLE
gracefully handle lack of training data

### ISSUE THREAD

**Issue by johannesjh** [beancount/smart_importer#6]
add a unit test and gracefully handle the case for when there are <= two accounts in the training data (I think that this would currently throw an error).

**Comment by zacchiro** [comment]
I'm not 100% the problem is related to this issue, but here we go:

I was expecting the decorators to work without `training_data=FILE` set, in case existing entries are passed (as the code seems to do that), but if I don't pass training_data (and I pass existing entries), I get this failure:
```
bean-extract -e current.beancount beancount.import INCOMING/sample/cmut-boobank.csv
DEBUG:smart_importer.predict_payees:The Decorator was applied to a class.
DEBUG:smart_importer.predict_postings:The Decorator was applied to a class.
;; -*- mode: beancount -*-
**** /home/zack/dati/ledger/INCOMING/sample/cmut-boobank.csv
DEBUG:smart_importer.predict_postings:About to call the importer's extract function to receive entries to be imported...
DEBUG:smart_importer.predict_payees:About to call the importer's extract function to receive entries to be imported...
DEBUG:smart_importer.machinelearning_helpers:Finished reading training data.
WARNING:smart_importer.predict_payees:Cannot train the machine learning model because the training data is empty.
WARNING:smart_importer.predict_payees:Cannot generate predictions or suggestions because there is no trained machine learning model.
DEBUG:smart_importer.machinelearning_helpers:Finished reading training data.
ERROR:root:Importer mybeancount.private.importers.cmut.Importer: "Assets:Cmut:Checking".extract() raised an unexpected error: 'NoneType' object is not iterable
ERROR:root:Traceback: Traceback (most recent call last):
  File "/home/zack/.local/lib/python3.6/site-packages/beancount/ingest/extract.py", line 176, in extract
    allow_none_for_tags_and_links=allow_none_for_tags_and_links)
  File "/home/zack/.local/lib/python3.6/site-packages/beancount/ingest/extract.py", line 70, in extract_from_file
    new_entries = importer.extract(file, **kwargs)
  File "/home/zack/.local/lib/python3.6/site-packages/smart_importer/predict_postings.py", line 88, in wrapper
    return decorator.enhance_transactions()
  File "/home/zack/.local/lib/python3.6/site-packages/smart_importer/predict_postings.py", line 100, in enhance_transactions
    for t in self.training_data
TypeError: 'NoneType' object is not iterable
```
Note that I'm sure existing entries are working fine without smart_importer, because bean-extract successfully deduplicate w.r.t. existing entries.

OTOH, if I pass both existing entries and an explicit training_data parameter, I get this different failure:
```
bean-extract -e current.beancount beancount.import INCOMING/sample/cmut-boobank.csv
DEBUG:smart_importer.predict_payees:The Decorator was applied to a class.
DEBUG:smart_importer.predict_postings:The Decorator was applied to a class.
;; -*- mode: beancount -*-
**** /home/zack/dati/ledger/INCOMING/sample/cmut-boobank.csv
DEBUG:smart_importer.predict_postings:About to call the importer's extract function to receive entries to be imported...
DEBUG:smart_importer.predict_payees:About to call the importer's extract function to receive entries to be imported...
DEBUG:smart_importer.machinelearning_helpers:Reading training data from file "current.beancount"...
DEBUG:smart_importer.machinelearning_helpers:Finished reading training data.
ERROR:root:Importer mybeancount.private.importers.cmut.Importer: "Assets:Cmut:Checking".extract() raised an unexpected error: object of type 'generator' has no len()
ERROR:root:Traceback: Traceback (most recent call last):
  File "/home/zack/.local/lib/python3.6/site-packages/beancount/ingest/extract.py", line 176, in extract
    allow_none_for_tags_and_links=allow_none_for_tags_and_links)
  File "/home/zack/.local/lib/python3.6/site-packages/beancount/ingest/extract.py", line 70, in extract_from_file
    new_entries = importer.extract(file, **kwargs)
  File "/home/zack/.local/lib/python3.6/site-packages/smart_importer/predict_postings.py", line 85, in wrapper
    decorator.imported_transactions = original_extract_function(self, file)
  File "/home/zack/.local/lib/python3.6/site-packages/smart_importer/predict_payees.py", line 84, in wrapper
    return decorator.enhance_transactions()
  File "/home/zack/.local/lib/python3.6/site-packages/smart_importer/predict_payees.py", line 99, in enhance_transactions
    elif len(self.training_data) < 2:
TypeError: object of type 'generator' has no len()
```

My importer does not have an explicitly defined `extract` method, as it subclasses beancount built-in csv.Importer, in case that's a factor.

I'm happy to submit this as a separate issue if appropriate.

**Comment by tarioch** [comment]
I'm pretty sure the factor is the extract method. Only very recently an overloaded version was introduced which passes the existing entries into the exporter. This is what is used.
All my imports use the new method and the passing of existing entries works fine.

The new method looks like this

```
def extract(self, file, existing_entries):
```

The standard csv extractor in beancount does not yet use the new method.

**Comment by tarioch** [comment]
Just to confirm, from where did you install smart_importer? Pypi or from git directly?
